SecretSanta/Models/MessageViewModel.cs
using System;

namespace SecretSanta.Models
{
    public class MessageViewModel
    {
        public long Id { get; set; }
        public string Label { get; set; }
        public bool OwnMessage { get; set; }
        public string MessageText { get; set; }
        public DateTime Timestamp { get; set; }
    }
}

SecretSanta/Controllers/LoginController.cs
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Resources;
using SecretSanta.Models;
using SecretSanta.Security;

namespace SecretSanta.Controllers
{
    [Authorize]
    public class LoginController : BaseController
    {
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(new LoginModel());
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(LoginModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var status = await HttpContext.GetOwinContext().Get<SantaSignInManager>().PasswordSignInAsync(model.Login, model.Password, true, false);
            switch (status)
            {
                case SignInStatus.Success:
                    return RedirectToAction(nameof(Index), "Home");
                case SignInStatus.LockedOut:
                    ModelState.AddModelError(Constants.GlobalModerError, Global.Login_LockedOut);
                    return View(model);
                //case SignInStatus.RequiresVerification:
                //    return RedirectToAction("TODO");
                case SignInStatus.Failure:
                    ModelState.AddModelError(Constants.GlobalModerError, Global.Login_Invalid);
                    return View(model);
                default:
                    throw new ArgumentOutOfRangeException();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Logout()
        {
            HttpContext.GetOwinContext().Authentication
                .SignOut(DefaultAuthenticationTypes.ApplicationCookie);

            return RedirectToAction("Index", "Home");
        }

    }
}

SecretSanta/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SecretSanta.Common.Interface;
using SecretSanta.Domain.Enums;
using SecretSanta.Helpers;
using SecretSanta.Models;
using SecretSanta.Security;

namespace SecretSanta.Controllers
{
    // TODO: This is candidate for full rewrite. Leaving in working but crappy state because of time constraints.
    [Authorize(Roles = SantaUserManager.UserRole)]
    public class MessagesController : BaseMessagesController
    {
        private readonly IMessageReadOnlyRepository _messageRepository;
        private readonly IMessageService _messageService;
        private readonly IUserRepository _userRepository;

        public MessagesController(IMessageReadOnlyRepository messageRepository, IUserRepository userRepository, IMessageService messageService)
        {
            _messageRepository = messageRepository;
            _userRepository = userRepository;
            _messageService = messageService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var userId = GetUserId();
            if (!userId.HasValue)
                return RedirectToAction("Index", "Home");

            var userMessages = _messageRepository.GetUserMessages(userId.Value);
            var model = new UserMessagesViewModel
            {
                WasAssigned = _userRepository.WasAssigned(),
                WithAssigned  = new List<MessageViewModel>(),
                WithGiftor = new List<MessageViewModel>(),
                WithAdmin = new List<MessageViewModel>()
            };

            foreach (var message in userMessages.OrderBy(m => m.Timestamp))
            {
                if (message.SenderId == userId)
                {
                    // From user, see in what role:
                    switch (message.SenderRole)
                    {
                        // for user messages, he can be User (with admin), Sender (with assigned) or Recipient (with his santa)
                        case MessageRole.User:
                            model.WithAdmin.Add(GetMessageViewModel(message, userId));
                            break;
                        case MessageRole.GiftSender:
                            model.WithAssigned.Add(GetMessageViewModel(message, userId));
                            break;
                        case MessageRole.GiftRecipient:
                            model.WithGiftor.Add(GetMessageViewModel(message, userId));
                            break;
                    }
                }
                else
                {
                    // from someone else, see in what role:
                    switch (message.SenderRole)
                    {
                        // for incoming messages, he can be Admin (with admin), Sender (with Santa) or Recipient (with assigned)
                        case MessageRole.Administrator:
                            model.WithAdmin.Add(GetMessageViewModel(message, userId));
                            break;
                        case MessageRole.GiftSender:
                            model.WithGiftor.Add(GetMessageViewModel(message, userId));
                            break;
                        case MessageRole.GiftRecipient:
                            model.WithAssigned.Add(GetMessageViewModel(message, userId));
                            break;
                    }
                }
            }

            return View(model);
        }



        [HttpGet]
        public ActionResult PostConversation(MessageRole sender, MessageRole recipient)
        {
            return View(new ConversationPostModel {SenderRole = sender, RecipientRole = recipient});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostConversation(ConversationPostModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var userId = GetUserId();
            if (!userId.HasValue)
                return RedirectToAction("Index", "Home");

            if(model.RecipientRole == MessageRole.Administrator)
                _messageService.SendMessageToAdmin(userId.Value, model.MessageText);
            else
                _messageService.SendMessageFromUserToUser(userId.Value, model.SenderRole, GetRecipient(model.RecipientRole, userId.Value), model.RecipientRole, model.MessageText);


            return RedirectToAction("Index");
        }

        private long GetRecipient(MessageRole modelRecipientRole, long userId)
        {
            switch (modelRecipientRole)
            {
                case MessageRole.GiftRecipient:
                    return _userRepository.GetAssignedPartnerIdForUser(userId) ??
                           throw new InvalidOperationException(
                               $"User ({userId}) that has not been in assignment tried to send a message to recipient");
                case MessageRole.GiftSender:
                    return _userRepository.GetUserAssignedTo(userId) ?? throw new InvalidOperationException(
                               $"User ({userId}) that has not been in assignment tried to send a message to recipient");
            }
            throw new ArgumentOutOfRangeException(nameof(modelRecipientRole),$"User ({userId}) requested recipient for role {modelRecipientRole.ToString()} which should not have happened");
        }
    }
}

SecretSanta/Controllers/UserController.cs
using System;
using System.Web.Mvc;
using AutoMapper;
using SecretSanta.Common.Interface;
using SecretSanta.Domain.Models;
using SecretSanta.Helpers;
using SecretSanta.Models;
using SecretSanta.Security;

namespace SecretSanta.Controllers
{
    [Authorize(Roles = SantaUserManager.AdminRole)]
    public class UserController : BaseController
    {
        private readonly IMapper _mapper;
        private readonly IUserRepository _userRepository;
        private readonly IConfigProvider _configProvider;
        private readonly IEmailService _emailService;

        public UserController(IUserRepository userRepository, IConfigProvider configProvider, IEmailService emailService, IMapper mapper)
        {
            _userRepository = userRepository;
            _configProvider = configProvider;
            _emailService = emailService;
            _mapper = mapper;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return
            View(_userRepository.GetAllUsersWithoutProtectedData());
        }

        [HttpGet]
        public ActionResult CreateUser()
        {
            return View(new RegistrationPostModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUser(RegistrationPostModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Password = null;
                model.RepeatPassword = null;
                return View(model);
            }

            // check fo existing user
            if (!_userRepository.CheckEmail(model.Email))
            {
                ModelState.AddModelError(nameof(RegistrationPostModel.Email), Resources.Global.EmailTaken);
                model.Password = null;
                model.RepeatPassword = null;
                return View(model);
            }

            if (model.Password != model.RepeatPassword)
            {
                ModelState.AddModelError(nameof(RegistrationPostModel.RepeatPassword), Resources.Global.Registration_Form_Repeat_Password_Invalid);
                model.Password = null;
                model.RepeatPassword = null;
                return View(model);
            }

            if (model.DateOfBirth.AddYears(_configProvider.MinimumAge) > DateTime.Today)
            {
                ModelState.AddModelError(nameof(RegistrationPostModel.DateOfBirth), Resources.Global.Registration_Form_DateOfBirth_NotEnough);
                model.Password = null;
                model.RepeatPassword = null;
                return View(model);
            }

            // set the correct fb uri:
            model.FacebookProfileUrl = FacebookUriHelper.GetUniformFacebookUri(model.FacebookProfileUrl);

            if (model.FacebookProfileUrl == null || !_userRepository.CheckFacebookProfileUri(model.FacebookProfileUrl))
            {
                ModelState.AddModelError(nameof(RegistrationPostModel.FacebookProfileUrl), Resources.Global.FacebookURL_Invalid);
                model.Password = null;
                model.RepeatPassword = null;
                return View(model);
            }

            // save to db
            var domainModel = _mapper.Map<SantaUser>(model);
            _userRepository.InsertUser(domainModel);

            _emailService.SendConfirmationEmail(domainModel);

            return View("Message", model: string.Format(Resources.Global.AdminUser_Created_Format, model.Email));
        }

        [HttpGet]
        public ActionResult RemoveUser(long id)
        {
            return View(_userRepository.GetUserWithoutProtectedData(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveUser(SantaUser user)
        {
            if (_userRepository.WasAssigned())
                return View("Message", model: Resources.Global.Message_CannotRemoveAccountAfterAssignment);

            _userRepository.DeleteUser(user.Id);
            return RedirectToAction("Index");
        }
    }
}

SecretSanta/Views/Shared/Message.cshtml
@model string

@{
    ViewBag.Title = $"{Resources.Global.SiteName} - {Resources.Global.SystemMessage}";
}

<h2>@Resources.Global.SystemMessage</h2>

<div class="alert alert-info">
    <p>@Model</p>
</div>

SecretSanta/Views/Shared/_BadgeCounter.cshtml
@model int

<span class="badge badge-default badge-pill">@Model</span>

SecretSanta/Views/Shared/_ConfirmationCell.cshtml
@model SecretSanta.Models.ConfirmationHelperModel

@if (Model.Confirmed)
{
    <td class="success">
        <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
        <span class="sr-only">Confirmed</span>
    </td>
}
else
{
    <td id="confirmation_@Model.UserId">
        <input type="hidden" name="id" value="@Model.UserId" aria-hidden="True"/>
        <button type="submit" class="btn btn-success" aria-label="Confirm">
            <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
        </button>
        <span id="loader_@Model.UserId" class="glyphicon glyphicon-repeat normal-right-spinner" style="display:none" aria-label="Loading"></span>
    </td>
}

SecretSanta/Views/Shared/_Layout.cshtml
@using SecretSanta.Models
@using SecretSanta.Security
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryajax")
    @* COOKIES INFO *@
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
    <script>
        window.addEventListener("load", function(){
            window.cookieconsent.initialise({
                "palette": {
                    "popup": {
                        "background": "#eaf7f7",
                        "text": "#5c7291"
                    },
                    "button": {
                        "background": "#56cbdb",
                        "text": "#ffffff"
                    }
                },
                "content": {
                    "message": "@Resources.Global.CookieBanner_Message",
                    "dismiss": "@Resources.Global.CookieBanner_Accept",
                    "link": "@Resources.Global.PrivacyPolicy",
                    "href": "@Url.Action("Index", "Privacy")"
                }
            })});
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(Resources.Global.SiteName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink(Resources.Global.Registration, "Index", "Registration")</li>
                    }
                    @if (User.IsInRole(SantaUserManager.AdminRole))
                    {
                        <li>@Html.ActionLink(Resources.Global.AdminIndex, "Index", "Admin")</li>
                        <li>@Html.ActionLink(Resources.Global.AdminUser, "Index", "User")</li>
                        <li>@Html.ActionLink(Resources.Global.Assignment, "Index", "Assignment")</li>
                        <li><a href="@Url.Action("Index", "Verification")">@Resources.Global.AdminUnconfirmed @Html.Action("GetAwaitingVerifications","Verification")</a></li>
                        <li>@Html.ActionLink(Resources.Global.AdminMessages, "Index", "AdminMessage")</li>
                    }
                    @if (User.IsInRole(SantaUserManager.UserRole))
                    {
                        <li>@Html.ActionLink(Resources.Global.AccountSettings, "Index", "Account")</li>
                        <li>@Html.ActionLink(Resources.Global.Messages, "Index", "Messages")</li>
                    }
                    @if (!User.IsInRole(SantaUserManager.AdminRole))
                    {
                        <li>@Html.ActionLink(Resources.Global.PrivacyPolicy, "Index", "Privacy")</li>
                        <li>@Html.ActionLink(Resources.Global.Rules, "Rules", "Home")</li>
                    }
                </ul>
                @if (User?.Identity?.IsAuthenticated != true)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
                            <ul id="login-dp" class="dropdown-menu">
                                <li>
                                    <div class="row">
                                        <div class="col-md-12">
                                            @using (Html.BeginForm("Index", "Login", FormMethod.Post, new {@role = "form", @id = "login-nav"}))
                                            {
                                                @Html.AntiForgeryToken()
                                                <div class="form-group">
                                                    <label class="sr-only" for="@nameof(LoginModel.Login)">@Resources.Global.Login</label>
                                                    <input type="text" class="form-control" id="@nameof(LoginModel.Login)" name="@nameof(LoginModel.Login)" placeholder="@Resources.Global.LoginName" required>
                                                </div>
                                                <div class="form-group">
                                                    <label class="sr-only" for="@nameof(LoginModel.Password)">@Resources.Global.Password</label>
                                                    <input type="password" class="form-control" id="@nameof(LoginModel.Password)" name="@nameof(LoginModel.Password)" placeholder="@Resources.Global.Password" required>
                                                    @*<div class="help-block text-right"><a href="">Forget the password ?</a></div>*@
                                                </div>
                                                <div class="form-group">
                                                    <button type="submit" class="btn btn-primary btn-block">@Resources.Global.Login</button>
                                                </div>
                                                @*<div class="checkbox">
                                                    <label>
                                                        <input type="checkbox"> keep me logged-in
                                                    </label>
                                                </div>*@
                                            }
                                        </div>
                                        <div class="bottom text-center">
                                            <a href="@Url.Action("ForgotPassword","Account")"><b>@Resources.Global.Menu_ForgotPassword</b></a>
                                        </div>
                                        <div class="bottom text-center">
                                            <a href="@Url.Action("Index","Registration")"><b>@Resources.Global.Registration</b></a>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <p class="navbar-text">@Resources.Global.Hello @ClaimHelper.GetUserName(User)</p>
                        </li>
                        <li>
                            @using (Html.BeginForm("Logout", "Login",FormMethod.Post,new {@class= "navbar-form navbar-right" }))
                            {
                                @Html.AntiForgeryToken()
                                <button type="submit" class="btn btn-link">@Resources.Global.Logout</button>
                            }
                        </li>
                    </ul>
                }
            </div>
        </div>
    </div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>@DateTime.Now.Year - @Resources.Global.SiteName</p>
    </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SecretSanta/Views/Shared/_SantaUserTableHeader.cshtml
@using SecretSanta.Domain.Models
@model SantaUser

<thead>
    <tr>
        <th>@Html.DisplayNameFor(m=>m.DisplayName)</th>
        <th>@Html.DisplayNameFor(m=>m.Email)</th>
        <th>@Html.DisplayNameFor(m=>m.FacebookProfileUrl)</th>
        <th>@Html.DisplayNameFor(m=>m.EmailConfirmed)</th>
        <th>@Html.DisplayNameFor(m=>m.AdminConfirmed)</th>
        <th></th>
    </tr>
</thead>

SecretSanta/Views/Shared/_UserTable.cshtml
@using SecretSanta.Models
@model IList<SecretSanta.Domain.Models.SantaUser>


@if (!Model.Any())
{
    <div class="alert alert-success">@ViewBag.NoDataMessage</div>
}
else
{
    <table class="table table-striped">
        @Html.Partial("_SantaUserTableHeader", Model.First())
        <tbody>
            @foreach (var adminDesc in Model)
            {
                <tr>
                    <td>@adminDesc.DisplayName</td>
                    <td>@adminDesc.Email</td>
                    <td><a href="@(new UriBuilder(adminDesc.FacebookProfileUrl).ToString())">@adminDesc.FacebookProfileUrl</a></td>

                    @if (adminDesc.EmailConfirmed)
                    {
                        <td class="success">
                            <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                            <span class="sr-only">Confirmed</span>
                        </td>
                    }
                    else
                    {
                        <td class="warning">
                            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                            <span class="sr-only">Awaiting confirmation</span>
                        </td>
                    }

                    @if (adminDesc.AdminConfirmed)
                    {
                        @Html.Partial("_ConfirmationCell", ConfirmationHelperModel.ConfirmedModel)
                    }
                    else
                    {
                        using (Ajax.BeginForm("AdminConfirmUser", "Verification", new { id = adminDesc.Id }, new AjaxOptions { InsertionMode = InsertionMode.ReplaceWith, UpdateTargetId = $"confirmation_{adminDesc.Id}", LoadingElementId = $"loader_{adminDesc.Id}" }))
                        {
                            @Html.AntiForgeryToken()
                            
                            @Html.Partial("_ConfirmationCell", ConfirmationHelperModel.UnconfirmedModel(adminDesc.Id));
                            
                        }

                    }
                    <td>
                        <a href="@Url.Action("RemoveUser","User",new{id=adminDesc.Id})" class="btn btn-warning"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>@Resources.Global.RemoveUser</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}