SecretSanta/Models/AssignmentViewModel.cs
namespace SecretSanta.Models
{
    public class AssignmentViewModel
    {
        public string FacebookProfileUrl { get; set; }
        public string FullName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Note { get; set; }
        public bool IsAdult { get; set; }
    }
}

SecretSanta/Models/SendAssignmentEmailsViewModel.cs
using System.Collections.Generic;

namespace SecretSanta.Models
{
    public class SendAssignmentEmailsViewModel
    {
        public IList<AssignmentEmailViewModel> Assignments { get; set; }
        public IList<AbandonedEmailViewModel> Abandonments { get; set; }
    }
}

SecretSanta/Controllers/AssignmentController.cs
using System.Collections.Concurrent;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Caching;
using System.Web.Hosting;
using System.Web.Mvc;
using SecretSanta.Common.Interface;
using SecretSanta.Common.Result;
using SecretSanta.Models;
using SecretSanta.Security;

namespace SecretSanta.Controllers
{
    [Authorize(Roles = SantaUserManager.AdminRole)]
    public class AssignmentController : BaseController
    {
        private const string AssignmentCacheKey = "secret_santa.last_assignment_result";

        private readonly IAssignmentService _assignmentService;
        private readonly IEmailService _emailService;

        public AssignmentController(IEmailService emailService, IAssignmentService assignmentService)
        {
            _emailService = emailService;
            _assignmentService = assignmentService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            if (_assignmentService.WasAssigned())
            {
                return View(_assignmentService.GetAssignments());
            }
            return View((AssignmentResult)null);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Assign()
        {
            if (_assignmentService.WasAssigned())
                return RedirectToAction("Index");

            // remove any previous
            HttpContext.Cache.Remove(AssignmentCacheKey);

            var assignments = _assignmentService.GenerateAssignments();
            // Save to cache
            HttpContext.Cache.Add(AssignmentCacheKey, assignments, null, Cache.NoAbsoluteExpiration,
                Cache.NoSlidingExpiration, CacheItemPriority.NotRemovable, null);

            return View("AssignmentGenerated", assignments);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveLastAssignment()
        {
            var assignments = (AssignmentResult) HttpContext.Cache.Get(AssignmentCacheKey);
            if (assignments == null)
                return View("Message",
                    model: Resources.Global.Assignments_NoAssignmentsInCache);
            
            _assignmentService.SaveAssignments(assignments);
            return View("AssignmentCompleted", assignments);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SendAssignmentEmails()
        {
            if (!_assignmentService.WasAssigned())
                return RedirectToAction("Index");

            var assignments = _assignmentService.GetAssignments();
            var assignmentModels = new ConcurrentBag<AssignmentEmailViewModel>();
            var abandonedModels = new ConcurrentBag<AbandonedEmailViewModel>();
            var parallelOptions = new ParallelOptions
            {
                MaxDegreeOfParallelism = 5
            };
            Parallel.ForEach(assignments.Assignments,parallelOptions,
                assignment =>
                {
                    var sender = assignments.UserDisplayById[assignment.GiverId];
                    var target = assignments.UserDisplayById[assignment.RecepientId];

                    var success = _emailService.SendAssignmentEmail(sender, target);
                    
                        assignmentModels.Add(new AssignmentEmailViewModel
                        {
                            SenderDisplayName = sender.DisplayName,
                            SenderEmail = sender.Email,
                            TargetDisplayName = target.DisplayName,
                            TargetEmail = target.Email,
                            Success = success
                        });
                    
                });
            Parallel.ForEach(assignments.Abandoned, parallelOptions,
                abandoned =>
                {
                    var user = assignments.UserDisplayById[abandoned.SantaUserId];
                    var success = _emailService.SendAbandonmentEmail(user,
                        abandoned.Reason);
                    abandonedModels.Add(new AbandonedEmailViewModel
                    {
                        DisplayName = user.DisplayName,
                        Email = user.Email,
                        Reason = abandoned.Reason,
                        Success = success
                    });
                    
                });

            var model = new SendAssignmentEmailsViewModel
            {
                Assignments = assignmentModels.ToArray(),
                Abandonments = abandonedModels.ToArray()
            };

            return View(model);
        }

    }
}

SecretSanta/Views/Assignment/AssignmentCompleted.cshtml
@using SecretSanta.Domain.Models
@model SecretSanta.Common.Result.AssignmentResult

@{
    ViewBag.Title = $"{Resources.Global.SiteName} - {Resources.Global.AssignmentCompleted}";
}


<h2>@Resources.Global.AssignmentCompleted</h2>

@Html.Partial("_AssignmentResult", Model)

@using (Html.BeginForm("SendAssignmentEmails","Assignment"))
{
@Html.AntiForgeryToken()
<button type="submit" class="btn btn-info">@Resources.Global.SendAssignmentEmails_Submit</button>
}

SecretSanta/Views/Assignment/AssignmentGenerated.cshtml
@using SecretSanta.Domain.Models
@model SecretSanta.Common.Result.AssignmentResult

@{
    ViewBag.Title = $"{Resources.Global.SiteName} - {Resources.Global.AssignmentGenerated}";
}


<h2>@Resources.Global.AssignmentGenerated</h2>

@Html.Partial("_AssignmentResult", Model)

@using (Html.BeginForm("SaveLastAssignment", "Assignment"))
{
    @Html.AntiForgeryToken()
    <input type="submit" value="@Resources.Global.Button_SaveLastAssignment"/>
}

SecretSanta/Views/Assignment/Index.cshtml
@model SecretSanta.Common.Result.AssignmentResult

@{
    ViewBag.Title = $"{Resources.Global.SiteName} - {Resources.Global.Assignment}";
}

<h2>@Resources.Global.Assignment</h2>

@if (Model != null)
{
    <div class="alert alert-info"><p>@Resources.Global.AssignmentDone</p></div>

    @Html.Partial("_AssignmentResult", Model)

    using (Html.BeginForm("SendAssignmentEmails","Assignment"))
    {
        @Html.AntiForgeryToken()
        <button type="submit" class="btn btn-info">@Resources.Global.SendAssignmentEmails_Submit</button>
    }
}
 else
{
    using (Html.BeginForm("Assign", "Assignment"))
    {
     @Html.AntiForgeryToken()
     <button type="submit" class="btn btn-info">@Resources.Global.Assignment</button>
 }
}

SecretSanta/Views/Assignment/SendAssignmentEmails.cshtml
@model SecretSanta.Models.SendAssignmentEmailsViewModel

@{
    ViewBag.Title = $"{Resources.Global.SiteName} - {Resources.Global.Assignment}";
}

<h2>@Resources.Global.Assignment</h2>

<table class="table table-striped">
    <caption>@Resources.Global.Assignments</caption>
    <thead>
    <tr>
        <th colspan="2">@Resources.Global.Giver</th>
        <th colspan="2">@Resources.Global.Recipient</th>
        <th>&nbsp;</th>
    </tr>
    <tr>
        <th>@Resources.Global.DisplayName</th>
        <th>@Resources.Global.Email</th>
        
        <th>@Resources.Global.DisplayName</th>
        <th>@Resources.Global.Email</th>
        
        <th>@Resources.Global.SendAssignmentEmails_Result</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var assignment in Model.Assignments)
    {
        <tr>
            <td>@assignment.SenderDisplayName</td>
            <td>@assignment.SenderEmail</td>
            <td>@assignment.TargetEmail</td>
            <td>@assignment.TargetDisplayName</td>
            @if (assignment.Success)
            {
                <td class="success">
                    <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                    <span class="sr-only">Sent</span>
                </td>
            }
            else
            {
                <td class="warning">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    <span class="sr-only">Failed</span>
                </td>
            }
        </tr>
    }
    </tbody>
</table>

<table class="table table-striped">
    <caption>@Resources.Global.AbandonedUsers</caption>
    <thead>
        <tr>
            <th>@Resources.Global.DisplayName</th>
            <th>@Resources.Global.Email</th>
            <th>@Resources.Global.Reason</th>
            <th>@Resources.Global.SendAssignmentEmails_Result</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var abandoned in Model.Abandonments)
        {
            <tr>
                <td>@abandoned.DisplayName</td>
                <td>@abandoned.Email</td>
                <td>@Html.Partial("DisplayTemplates/AbandonmentReason", abandoned.Reason)</td>
                @if (abandoned.Success)
                {
                    <td class="success">
                        <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                        <span class="sr-only">Sent</span>
                    </td>
                }
                else
                {
                    <td class="warning">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        <span class="sr-only">Failed</span>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

SecretSanta/Views/Assignment/_AssignmentResult.cshtml
@using SecretSanta.Domain.Models
@model SecretSanta.Common.Result.AssignmentResult

@helper GenerateRow(Assignment assignment)
{
var giver = Model.UserDisplayById[assignment.GiverId];
var recipient = Model.UserDisplayById[assignment.RecepientId];
    <tr>
        <td>@giver.DisplayName</td>
        <td>@giver.Email</td>
        <td>@giver.Country</td>
        <td>@giver.SendAbroad</td>
        <td>@recipient.DisplayName</td>
        <td>@recipient.Email</td>
        <td>@recipient.Country</td>
        <td>@recipient.SendAbroad</td>
    </tr>
}

@helper GenerateRow(Abandoned abandoned)
{
var user = Model.UserDisplayById[abandoned.SantaUserId];

    <tr>
        <td>@user.DisplayName</td>
        <td>@user.Email</td>
        <td>@user.Country</td>
        <td>@user.SendAbroad</td>
        <td>@abandoned.Reason</td>
    </tr>
}
<table class="table table-striped">
    <caption>@Resources.Global.Assignments</caption>
    <thead>
    <tr>
        <th colspan="3">@Resources.Global.Giver</th>
        <th colspan="3">@Resources.Global.Recipient</th>
    </tr>
    <tr>
        <th>@Resources.Global.DisplayName</th>
        <th>@Resources.Global.Email</th>
        <th>@Resources.Global.Country</th>
        <th>@Resources.Global.WillSendAbroad</th>
        
        <th>@Resources.Global.DisplayName</th>
        <th>@Resources.Global.Email</th>
        <th>@Resources.Global.Country</th>
        <th>@Resources.Global.WillSendAbroad</th>
    </tr>
    </thead>
    <tbody>
        @foreach (var assignment in Model.Assignments)
        {
            @GenerateRow(assignment)
        }
    </tbody>
</table>

@if (Model.Abandoned.Any())
{
    <div class="panel panel-warning">
        <table class="table table-striped">
            <caption>@Resources.Global.AbandonedUsers</caption>
            <thead>
                <tr>
                    <th>@Resources.Global.DisplayName</th>
                    <th>@Resources.Global.Email</th>
                    <th>@Resources.Global.Country</th>
                    <th>@Resources.Global.WillSendAbroad</th>
                    <th>@Resources.Global.Reason</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var abandoned in Model.Abandoned)
                {
                    @GenerateRow(abandoned)
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="panel panel-success">
        <p>@Resources.Global.AllUsersMatched</p>
    </div>
}