SecretSanta/Models/SettingsViewModel.cs
using System.ComponentModel.DataAnnotations;
using Resources;

namespace SecretSanta.Models
{
    public class SettingsViewModel
    {
        [Display(Name = "RegistrationOpen", ResourceType = typeof(Global))]
        public bool RegistrationOpen { get; set; }
    }
}

SecretSanta/Controllers/SettingController.cs
using System.Web.Mvc;
using SecretSanta.Common.Interface;
using SecretSanta.Models;

namespace SecretSanta.Controllers
{
    [Authorize]
    public class SettingController : BaseController
    {
        private readonly ISettingsRepository _settingsRepository;

        public SettingController(ISettingsRepository settingsRepository)
        {
            _settingsRepository = settingsRepository;
        }

        [HttpGet]
        public ActionResult Index()
        {
            //_mapper<SettingsViewModel>(_settingsRepository)
            var model = new SettingsViewModel{RegistrationOpen = _settingsRepository.RegistrationOpen};
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CloseRegistration()
        {
            _settingsRepository.RegistrationOpen = false;
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult OpenRegistration()
        {
            _settingsRepository.RegistrationOpen = true;
            return RedirectToAction("Index");
        }
    }
}

SecretSanta/Views/Setting/Index.cshtml
@model SecretSanta.Models.SettingsViewModel
@{
    ViewBag.Title = $"{Resources.Global.SiteName} - {Resources.Global.Settings}";
}

<h2>@Resources.Global.Settings</h2>

<table class="table table-striped">
    <thead>
    <tr>
        <th>@Resources.Global.SettingName</th>
        <th>@Resources.Global.SettingValue</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>@Html.DisplayNameFor(m=>m.RegistrationOpen)</td>
        <td>@Html.DisplayFor(m=>m.RegistrationOpen)</td>
        <td>
            @if (Model.RegistrationOpen)
            {
                using (Html.BeginForm("CloseRegistration","Setting"))
                {
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-warning"><span class="glyphicon glyphicon-remove"></span>@Resources.Global.CloseRegistration</button>
                }
            }
            else
            {
                using (Html.BeginForm("OpenRegistration", "Setting"))
                {
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-check"></span>@Resources.Global.OpenRegistration</button>
                }
            }
        </td>
    </tr>
    </tbody>
</table>